### ISSUE TITLE
How to parse QR code?

### ISSUE THREAD

**Issue by zhaixing724** [knieriem/gs1qr#1]
It seems that it is possible to add a decoding function to get the data of the QR code?

**Comment by knieriem** [comment]
It would possibly work using https://github.com/makiuchi-d/gozxing for scanning an image, decoding the QR code, like this:

	bmp, _ := gozxing.NewBinaryBitmapFromImage(img)
	
	qrReader := qrcode.NewQRCodeReader()
	result, _ := qrReader.Decode(bmp, nil)

When decoding a QR code that was created using the [example data], the code sequence

	b := result.GetRawBytes()
	fmt.Printf("raw: % x\n", b)

	text := result.GetText()
	fmt.Printf("text: %q\n", text)

will produce the following output:

    raw: 51 05 00 a5 65 38 00 00 12 d8 02 07 b4 3a 3a 38 1d 17 97 b0 b1 31 97 37 32 ba 0e 90 18 16 de fc 9a 20 83 35 db 0d c3 30 b6 e0 ec 11

    text: "01034531200000118200http://abc.net\x1d10XYZ\x1d4109501101020917"

Splitting the text string at the correct positions, the original data can be extracted:

    [{01 03453120000011} {8200 http://abc.net} {10 XYZ} {410 9501101020917}]

With a bit of work, it should be possible to write a decoder that returns an `[]ai.Elem` slice.

[example data]: https://github.com/knieriem/gs1qr/blob/master/example/gs1qr/data

**Comment by zhaixing724** [comment]
> With a bit of work, it should be possible to write a decoder that returns an []ai.Elem slice.

It works great, thank you so much!
